e3_1/Models/Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace e3_1.Models
{
    public class Article
    {
        public int ArticleID { get; set; }
        public string Name { get; set; }

        //[DataType(DataType.Date)]
        public DateTime Date { get; set; }
        public string Text { get; set; }

        public virtual List<Review> Reviews { get; set; }
    }
}

e3_1/Models/ArticleContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace e3_1.Models
{
    public class ArticleContext: DbContext
    {
        public ArticleContext()
        {        
            Database.SetInitializer<ArticleContext>(new DropCreateDatabaseIfModelChanges<ArticleContext>());
        }
        public DbSet<Article> Articles { get; set; }
        public DbSet<Review> Reviews { get; set; }
    }
}

e3_1/Models/ArticleRepository.cs
using DataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace e3_1.Models
{
    public class ArticleRepository: Repository <Article>
    {
        public ArticleRepository() : base(new ArticleContext())
        { }

        public List<Review> GetReviews (int ArticleId)
        {
            Article article = this.Get(ArticleId);
            if (article !=null)
            {
                return article.Reviews;
            }
            else
            {
                return null;
            }
        }
    }
}

e3_1/Models/Profile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace e3_1.Models
{
     public class Profile
    {
        public string Name { get; set; }

        public int Age { get; set; }

        public bool Single { get; set; }

        public bool NoSingle { get; set; }

        public bool None { get; set; }
        public bool High_school { get; set; }
        public bool Bachelor { get; set; }
        public bool Master { get; set; }
        public bool Phd { get; set; }
    }
}

e3_1/Models/Review.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace e3_1.Models
{
    public class Review
    {
        public int ReviewID { get; set; }
        public DateTime Date { get; set; }
        public string Text { get; set; }

        public int ArticleId { get; set; }
        public virtual Article Article { get; set; }
    }
}

e3_1/Models/ReviewContainer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace e3_1.Models
{
    public class ReviewContainer
    {
        public static List<Review> reviews = new List<Review>();

    }
}

e3_1/ViewModels/ArticlePreview.cs
using e3_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace e3_1.ViewModels
{
    public class ArticlePreview
    {
        public Article Article { get; set; }

        public String Preview { get { return Article.Text.Length < 200 ? Article.Text : Article.Text.Substring(0, 200); } }
    }
}

e3_1/Controllers/ArticleController.cs
using e3_1.Models;
using e3_1.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace e3_1.Controllers
{
    public class ArticleController : Controller
    {
        private ArticleRepository repository = new ArticleRepository();
        // GET: Article
        public ActionResult Index()
        {
            var allArticles = repository.GetAll();
            List<ArticlePreview> articlePreviews = new List<ArticlePreview>();
            foreach (var article in allArticles)
            {
                var articlePreview = new ArticlePreview{ Article = article};
                articlePreviews.Add(articlePreview);
            }


            return View(articlePreviews);
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost()]
        public ActionResult Create(Article article)
        {
            if (!ModelState.IsValid) return View(article);

            repository.Add(article);
            repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var article = repository.Get(id);
            if (article == null) return HttpNotFound();
            else return View(article);
        }

        [HttpPost()]
        public ActionResult Edit(Article article)
        {
            if (!ModelState.IsValid) return View(article);

            repository.Update(article);
            repository.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Review(int id)
        {
            ViewBag.ArticleId = id;
            return View(repository.GetReviews(id));
        }

        public ActionResult CreateReview(int id)
        {
            ViewBag.ArticleId = id;
            return View();
        }

        [HttpPost]
        public ActionResult CreateReview(Review review)
        {
            if (!ModelState.IsValid) return View(review);

            Article article = repository.Get(review.ArticleId);
            if (article != null)
            {
                review.Date = DateTime.Now;
                article.Reviews.Add(review);
                repository.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Profile()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public ActionResult Profile(Profile profile)
        {
            TempData["profile"] = profile;
            return RedirectToAction("ProfileResult");
        }

        public ActionResult ProfileResult()
        {
            var profile = TempData["profile"] as Profile;
            if (profile != null)
            {
                ViewBag.Name = profile.Name;
                ViewBag.Age = profile.Age;
                ViewBag.MaritalStatus = profile.Single ? "single" : "married";
                List<string> edu = new List<string>();
                if (profile.None)
                {
                    edu.Add("none education");
                }
                if (profile.High_school)
                {
                    edu.Add("high school");
                }
                if (profile.Bachelor)
                {
                    edu.Add("barchelor");
                }
                if (profile.Master)
                {
                    edu.Add("master");
                }
                if (profile.Phd)
                {
                    edu.Add("phd");
                }
                ViewBag.edu = edu;
            }

            return View();
        }
    }
}

e3_1/Views/Article/Create.cshtml
@model e3_1.Models.Article

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Article</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

e3_1/Views/Article/CreateReview.cshtml
@model e3_1.Models.Review
@{
    ViewBag.Title = "Create";
}

<h2>Create Review</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ArticleId, new { Value = ViewBag.ArticleId })

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

e3_1/Views/Article/Edit.cshtml
@model e3_1.Models.Article

@{
    ViewBag.Title = "Edit";
}



<h2>Edit</h2>

@if (!String.IsNullOrEmpty(ViewBag.Message))
{
    <h3 style="color:red">@ViewBag.Message</h3>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Article</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ArticleID)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

e3_1/Views/Article/Index.cshtml
@model IEnumerable<e3_1.ViewModels.ArticlePreview>

@{
    ViewBag.Title = "Index";
}

@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>list article</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Article.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Article.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Article.Text)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Article.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Article.Date)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Preview)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Article.ArticleID }) |
        @Html.ActionLink("Review", "Review", new { id = item.Article.ArticleID })
    </td>
</tr>
}

</table>

e3_1/Views/Article/Profile.cshtml
@{
    ViewBag.Title = "Profile";
}

<h2>fill out a form</h2>
@model e3_1.Models.Profile
@using (Html.BeginForm("Profile", "Article", FormMethod.Post))
{
    <h3>name:</h3>
    @Html.TextBoxFor(m => m.Name)
    <h3>age:</h3>
    @Html.TextBoxFor(m => m.Age)
    <br />
    <br />
    <h3>married</h3>
    @Html.RadioButtonFor(m => m.Single, true)<span>single</span>
    <br />
    @Html.RadioButtonFor(m => m.Single, false)<span>married</span>
    <br />
    <br />
    <h3>education</h3>
    @Html.CheckBoxFor(m => m.None)<span>none</span>
    <br />
    @Html.CheckBoxFor(m => m.High_school)<span>high_school</span>
    <br />
    @Html.CheckBoxFor(m => m.Bachelor)<span>bachelor</span>
    <br />
    @Html.CheckBoxFor(m => m.Master)<span>master</span>
    <br />
    @Html.CheckBoxFor(m => m.Phd)<span>phd</span>
    <br />
    <br />
    <input type="submit" name="Button" value="Submit" />
}

e3_1/Views/Article/ProfileResult.cshtml
@{
    ViewBag.Title = "ProfileResult";
}
@using e3_1.Controllers
<ul>
    <li>
        name: @ViewBag.Name
    </li>
    <li>
        age: @ViewBag.Age
    </li>
    <li>
        marital_status: @ViewBag.MaritalStatus
    </li>
    <li>
        education:
        @if (ViewBag.edu != null)
        {
            @Html.CreateOrderedList(ViewBag.edu as List<string>);
        }

    </li>

</ul>

e3_1/Views/Article/Review.cshtml
@model IEnumerable<e3_1.Models.Review>

@{
    ViewBag.Title = "Review";
}

<h2>Review</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ReviewID }) |
                </td>
            </tr>
        }
    }
</table>

@Html.ActionLink("Create review", "CreateReview", new { id = ViewBag.ArticleId})

e3_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="header_div">
            <h2>Modern company</h2>
        </div>
    </header>
    <div class="loyout">
        <div class="sidebar">
            <ul>
                <li>@Html.ActionLink("Article", "Index", "Article")</li>
                <li>@Html.ActionLink("Review", "Review", "Article")</li>
                <li>@Html.ActionLink("Profile", "Profile", "Article")</li>
            </ul>
        </div>
        <div class="content">
            @RenderBody()
            <hr />
            <footer>
                <div class="footer_div">
                    <p>&copy; @DateTime.Now.Year - copyright. back to top</p>
                </div>
            </footer>
        </div>
    </div>
    
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Article", "Index", "Article")</li>
                    <li>@Html.ActionLink("Review", "Review", "Article")</li>
                    <li>@Html.ActionLink("Profile", "Profile", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
        
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - copyright. back to top</p>
        </footer>
    </div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>